[2024-08-21T22:16:04.275+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T22:16:04.294+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_spark_tasks.stream_to_postgres manual__2024-08-21T22:07:07.364170+00:00 [queued]>
[2024-08-21T22:16:04.302+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_spark_tasks.stream_to_postgres manual__2024-08-21T22:07:07.364170+00:00 [queued]>
[2024-08-21T22:16:04.302+0000] {taskinstance.py:2856} INFO - Starting attempt 3 of 3
[2024-08-21T22:16:04.313+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): stream_to_postgres> on 2024-08-21 22:07:07.364170+00:00
[2024-08-21T22:16:04.320+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-21T22:16:04.321+0000] {standard_task_runner.py:72} INFO - Started process 394 to run task
[2024-08-21T22:16:04.322+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_spark_tasks', 'stream_to_postgres', 'manual__2024-08-21T22:07:07.364170+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpouo6rzzp']
[2024-08-21T22:16:04.323+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask stream_to_postgres
[2024-08-21T22:16:04.358+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_spark_tasks.stream_to_postgres manual__2024-08-21T22:07:07.364170+00:00 [running]> on host 2b775d69f181
[2024-08-21T22:16:04.452+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_spark_tasks' AIRFLOW_CTX_TASK_ID='stream_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T22:07:07.364170+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T22:07:07.364170+00:00'
[2024-08-21T22:16:04.453+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-21T22:16:04.454+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-21T22:16:04.454+0000] {logging_mixin.py:190} INFO - Current task name:stream_to_postgres state:running start_date:2024-08-21 22:16:04.294810+00:00
[2024-08-21T22:16:04.454+0000] {logging_mixin.py:190} INFO - Dag name:docker_spark_tasks and current dag run status:running
[2024-08-21T22:16:04.455+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T22:16:04.456+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T22:16:04.457+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec node-master /bin/bash && ./home/spark/src/spark/submit.sh stream_to_postgres.py']
[2024-08-21T22:16:04.476+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T22:16:04.581+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: ./home/spark/src/spark/submit.sh: No such file or directory
[2024-08-21T22:16:04.581+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-08-21T22:16:04.592+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-08-21T22:16:04.596+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-21T22:16:04.596+0000] {logging_mixin.py:190} INFO - Task start:2024-08-21 22:16:04.294810+00:00 end:2024-08-21 22:16:04.595527+00:00 duration:0.300717
[2024-08-21T22:16:04.596+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): stream_to_postgres> dag:<DAG: docker_spark_tasks> dagrun:<DagRun docker_spark_tasks @ 2024-08-21 22:07:07.364170+00:00: manual__2024-08-21T22:07:07.364170+00:00, state:running, queued_at: 2024-08-21 22:07:07.377268+00:00. externally triggered: True>
[2024-08-21T22:16:04.596+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2024-08-21T22:16:04.597+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=docker_spark_tasks, task_id=stream_to_postgres, run_id=manual__2024-08-21T22:07:07.364170+00:00, execution_date=20240821T220707, start_date=20240821T221604, end_date=20240821T221604
[2024-08-21T22:16:04.607+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T22:16:04.607+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task stream_to_postgres (Bash command failed. The command returned a non-zero exit code 127.; 394)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-08-21T22:16:04.655+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-21T22:16:04.674+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T22:16:04.677+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
