[2024-08-21T22:00:23.819+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-21T22:00:23.838+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_spark_tasks.kafka_stream manual__2024-08-21T21:42:16.253919+00:00 [queued]>
[2024-08-21T22:00:23.847+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_spark_tasks.kafka_stream manual__2024-08-21T21:42:16.253919+00:00 [queued]>
[2024-08-21T22:00:23.847+0000] {taskinstance.py:2856} INFO - Starting attempt 6 of 6
[2024-08-21T22:00:23.860+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): kafka_stream> on 2024-08-21 21:42:16.253919+00:00
[2024-08-21T22:00:23.866+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=466) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-21T22:00:23.867+0000] {standard_task_runner.py:72} INFO - Started process 471 to run task
[2024-08-21T22:00:23.868+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_spark_tasks', 'kafka_stream', 'manual__2024-08-21T21:42:16.253919+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpitb3czus']
[2024-08-21T22:00:23.869+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask kafka_stream
[2024-08-21T22:00:23.904+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_spark_tasks.kafka_stream manual__2024-08-21T21:42:16.253919+00:00 [running]> on host ef4b9e98cc8c
[2024-08-21T22:00:23.960+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_spark_tasks' AIRFLOW_CTX_TASK_ID='kafka_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T21:42:16.253919+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T21:42:16.253919+00:00'
[2024-08-21T22:00:23.961+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-21T22:00:23.961+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-21T22:00:23.961+0000] {logging_mixin.py:190} INFO - Current task name:kafka_stream state:running start_date:2024-08-21 22:00:23.839136+00:00
[2024-08-21T22:00:23.961+0000] {logging_mixin.py:190} INFO - Dag name:docker_spark_tasks and current dag run status:running
[2024-08-21T22:00:23.962+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-21T22:00:23.962+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-21T22:00:23.963+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec node-master /usr/bin/python /home/spark/src/kafka/kafka_stream.py']
[2024-08-21T22:00:23.974+0000] {subprocess.py:86} INFO - Output:
[2024-08-21T22:00:23.987+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-08-21T22:00:23.990+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-08-21T22:00:23.998+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-21T22:00:24.001+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-21T22:00:24.002+0000] {logging_mixin.py:190} INFO - Task start:2024-08-21 22:00:23.839136+00:00 end:2024-08-21 22:00:24.001441+00:00 duration:0.162305
[2024-08-21T22:00:24.002+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): kafka_stream> dag:<DAG: docker_spark_tasks> dagrun:<DagRun docker_spark_tasks @ 2024-08-21 21:42:16.253919+00:00: manual__2024-08-21T21:42:16.253919+00:00, state:running, queued_at: 2024-08-21 21:55:19.188115+00:00. externally triggered: True>
[2024-08-21T22:00:24.002+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-08-21T22:00:24.002+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=docker_spark_tasks, task_id=kafka_stream, run_id=manual__2024-08-21T21:42:16.253919+00:00, execution_date=20240821T214216, start_date=20240821T220023, end_date=20240821T220024
[2024-08-21T22:00:24.011+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-21T22:00:24.011+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task kafka_stream (Bash command failed. The command returned a non-zero exit code 1.; 471)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-21T22:00:24.041+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-21T22:00:24.052+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-21T22:00:24.053+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
